export {default as Hero} from './Hero'
export {default as Testimonial} from './Testimonial'
export {default as HorizontalProducts} from './HorizontalProducts'
export {default as Collections} from './Collections'
export {default as Incentive} from './Incentive'
export {default as TestimonialsGrid} from './TestimonialsGrid'
export {default as Signup} from './Signup'