const gql = String.raw


export const getCustomer = gql`
query customer($token:String!){
  customer(customerAccessToken: $token) {
    id
    firstName
    lastName
    acceptsMarketing
    email
    orders(first:50){
      nodes{
        lineItems(first:50){
          nodes{
            quantity
            variant{
              product{
                title
                productType
								featuredImage{
                  url
                  altText
                }
                compareAtPriceRange{
                  minVariantPrice{
                    amount
                    currencyCode
                  }
                  maxVariantPrice{
                    amount
                    currencyCode
                  }
                }
              }
              title
              image{
                url
                altText
              }
            }
          }
        }
        id
        orderNumber
        subtotalPriceV2{
          amount
          currencyCode
        }
        totalPriceV2{
          amount
          currencyCode
				}
        totalRefundedV2{
          amount
          currencyCode
        }
        totalTaxV2{
          amount
          currencyCode
        }
        totalShippingPriceV2{
          amount
          currencyCode
        }
        shippingDiscountAllocations{
          allocatedAmount{
            amount
            currencyCode
          }
        }
        processedAt
        currentSubtotalPrice{
          amount
          currencyCode
        }
        canceledAt
        shippingAddress{
          firstName
          lastName
          address1
          address2
          zip
          province
          city
          country
				}
        fulfillmentStatus
      }
    }
  }
}
`