const gql = String.raw


export const viewProductByHandle = gql`
query Product($handle: String!) {
  product(handle:$handle) {
    id
    title
    totalInventory
    handle
    collections(first:10){
      nodes{
        id
        handle
        title
      }
    }
    tags
    seo{
      title
      description
    }
    compareAtPriceRange{
      maxVariantPrice{
        amount
        currencyCode
      }
      minVariantPrice{
        amount
        currencyCode
      }
    }
    options{
      name
      values
    }
    priceRange{
      maxVariantPrice{
        amount
        currencyCode
			}
      minVariantPrice{
        amount
        currencyCode
      }
    }
    descriptionHtml
    media(first: 50) {
      nodes{
        ...on MediaImage{
          image{
            url
            altText
          }
        }
        ... on Video{
					sources{
            url
          }
          previewImage{
            url
            altText
          }
        }
      }
    }
    variants(first:100){
      nodes{
        quantityAvailable
        id
        priceV2{
          amount
          currencyCode
        }
        image{
					url
          altText
        }
        selectedOptions{
          name
          value
        }
			}
    }
    details: metafield(namespace: "product", key: "details") {
    	value
    	type
  	}
    learnmore: metafield(namespace: "product", key: "learn_more") {
    	value
    	type
  	}
    useCases:metafield(namespace:"product",key:"use_cases"){
      value 
      type
    }
    orderWithin:metafield(namespace:"product",key:"order_within"){
      value
      type
    }
    deliveryBusinessDays:metafield(namespace:"product",key:"delivery_business_days"){
      value
      type
    }
    coupon:metafield(namespace:"product",key:"coupon"){
      value
      type
		}
    crossSell:metafield(namespace:"product",key:"cross_sell"){
      value
      type
    }
    seoTags:metafield(namespace:"product",key:"seo_tags"){
      value
      type
    }
    sizeGuide:metafield(namespace:"product",key:"sizeguide"){
      value
      type
    }
  }
}
`